services:
  - type: web
    name: red-dragon-bot
    env: node
    plan: free
    buildCommand: npm install && npm --prefix CypherX/CypherX-main install
    startCommand: node index.js
    envVars:
      - key: ACCESS_CODE
        value: REDDRAGON2024
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 3000
